repos:
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3.9
      exclude : '''
      /(
      \.venv
      | tests/
      )/
      '''
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: debug-statements

  - repo: https://github.com/sqlfluff/sqlfluff
    rev: 0.7.0a8
    hooks:
    - id: sqlfluff-lint
    - id: sqlfluff-fix
